---
# Default Etcd directory
etcd_data_dir: /var/lib/etcd
etcd_log_dir: /var/log/etcd
etcd_bin_dir: /usr/local/bin
etcd_sbin_dir: /usr/local/sbin
etcd_config_dir: /etc/etcd

# Etcd package requirements
etcd_packages: []

# Etcd version
etcd_version: "3.5.2"
etcd_url: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
etcd_checksum_url: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/SHA256SUMS"

# Default Etcd ports values
etcd_defaults:
  port: 2379
  peer_port: 2380
  metrics_port: 2381

# Metrics - https://etcd.io/docs/v3.5/op-guide/configuration/#profiling-and-monitoring
## Enable metrics
etcd_enable_metrics: true
## Set level of detail for exported metrics, specify 'extensive' to include server side grpc histogram metrics.
etcd_metrics: basic

# TLS / SSL
## Enable TLS / SSL
etcd_enable_ssl: true

## certificates files
etcd_cert_cafile: "{{ etcd_config_dir}}/ca.crt"
etcd_server_cert_file: "{{ etcd_config_dir}}/server.crt"
etcd_server_cert_key: "{{ etcd_config_dir}}/server.key"
etcd_peer_cert_file: "{{ etcd_config_dir}}/peer.crt"
etcd_peer_cert_key: "{{ etcd_config_dir}}/peer.key"

# etcd user / group
etcd_user: etcd
etcd_group: etcd

# Time (in milliseconds) of a heartbeat interval.
etcd_heartbeat_interval: 100

# Database management
## Compaction - Default disabled
etcd_compaction_retention: 0
etcd_compaction_mode: 'periodic'

# Database snapshot
## Number of committed transactions to trigger a snapshot to disk.
etcd_snapshot_count: 100000
## Maximum number of snapshots - unlimited 0
etcd_max_snapshots: 10

# Log options - https://etcd.io/docs/v3.5/op-guide/configuration/#logging
## Default logger
etcd_log_logger: zap
etcd_log_outputs: "{{ etcd_log_dir }}/etcd.log"
## Default log level
etcd_log_level: info
## Enable log rotation
etcd_log_rotation: true
etcd_log_rotation_config:
  maxsize: 100
  maxage: 1
  maxbackups: 180
  localtime: true
  compress: true

# etcd cluster configuration
## cluster token
etcd_cluster_token: cluster-token-to-change
## cluster initial state
etcd_cluster_state: new

## cluster initial election - to fast-forward initial election ticks on boot for faster election.
etcd_initial_election_tick_advance: true
## Time (in milliseconds) for an election to timeout.
etcd_election_timeout: 1000

## cluster peer
etcd_cluster: []
# etcd_cluster:
#   - fqdn:                         Required:  etcd node fqdn
#     port:                         Optionnal: etcd port number         - Default: (etcd_defaults.port)
#     peer_port:                    Optionnal: etcd peer port number    - Default: (etcd_defaults.peer_port)
#     metrics_port:                 Optionnal: etcd metrics port number - Default: (etcd_defaults.metrics_port)