---
## systemd - reload
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

## etcd - restart
- name: restart etcd
  ansible.builtin.service:
    name: etcd
    state: restarted
