---
## systemd - reload
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

## etcd - enable
- name: enable etcd
  ansible.builtin.service:
    name: etcd
    enabled: true

## etcd - enable start
- name: enable start etcd
  ansible.builtin.service:
    name: etcd
    enabled: true
    state: started

## etcd - restart
- name: restart etcd
  ansible.builtin.service:
    name: etcd
    state: restarted

## etcd - disable
- name: disable etcd
  ansible.builtin.service:
    name: etcd
    enabled: false
    state: stopped
