---
# Etcd version
etcd_version: "3.5.6"

# Metrics - https://etcd.io/docs/v3.5/op-guide/configuration/#profiling-and-monitoring
## Enable metrics
etcd_enable_metrics: true
## Set level of detail for exported metrics, specify 'extensive' to include server side grpc histogram metrics.
etcd_metrics: basic
## Metrics server list allowed to pull metrics (fqdn)
etcd_metrics_server: []
## Metrics server removed list (fqdn)
etcd_metrics_server_remove: []

# TLS / SSL
## Enable TLS / SSL - https://etcd.io/docs/v3.5/op-guide/security/
etcd_enable_ssl: false

## Enable selfsigned certicicate
etcd_auto_tls: false
## Selfsigned certificate validity in year
etcd_auto_tls_validity: 5

## Enable client cert auth
### => Not valid with etcd_auto_tls == true
etcd_enable_ssl_clientauth: true

## certificates files
etcd_cert_cafile: "{{ etcd_config_dir }}/ca.crt"
etcd_cert_client_cafile: "{{ etcd_cert_cafile }}"
etcd_cert_peer_cafile: "{{ etcd_cert_cafile }}"
etcd_server_cert_file: "{{ etcd_config_dir }}/server.crt"
etcd_server_cert_key: "{{ etcd_config_dir }}/server.key"
etcd_peer_cert_file: "{{ etcd_config_dir }}/peer.crt"
etcd_peer_cert_key: "{{ etcd_config_dir }}/peer.key"


# Time (in milliseconds) of a heartbeat interval.
etcd_heartbeat_interval: 100

# Database management
## Compaction - Default disabled
etcd_compaction_retention: 0
etcd_compaction_mode: 'periodic'

# Database snapshot
## Number of committed transactions to trigger a snapshot to disk.
etcd_snapshot_count: 100000
## Maximum number of snapshots - unlimited 0
etcd_max_snapshots: 10

# Database wals
## Maximum number of wal files - unlimited 0
etcd_max_wals: 10

# Log options - https://etcd.io/docs/v3.5/op-guide/configuration/#logging
## Default logger
etcd_log_logger: zap
etcd_log_outputs: "{{ etcd_log_dir }}/etcd.log"
## Default log level
etcd_log_level: info
## Enable log rotation
etcd_log_rotation: true
etcd_log_rotation_config:
  maxsize: 100
  maxage: 1
  maxbackups: 180
  localtime: true
  compress: true

# etcd cluster configuration
## cluster limit learner member
etcd_cluster_max_learner_member: 1
## cluster token
etcd_cluster_token: cluster-token-to-change
## cluster state
### Possible values: new, existing
etcd_cluster_state: existing

## cluster initial election - to fast-forward initial election ticks on boot for faster election.
etcd_initial_election_tick_advance: true
## Time (in milliseconds) for an election to timeout.
etcd_election_timeout: 1000

## etcd extra args to add
etcd_extra_args: []

## cluster peer
etcd_cluster: []
# etcd_cluster:
#   fqdn:                  Required  : String - member fqdn
#     state:               Optionnal : String - Member state to achieve regarding the cluster - Values (none, add, remove) - Default ( 'none' )
#                                               none   : no action
#                                               add    : add this member to the cluster
#                                               remove : remove this member from the cluster
#                             ===> https://etcd.io/docs/v3.5/op-guide/runtime-configuration/
#     function:            Optionnal : String - Member role in the cluster - Values (voting, learner) - Default ( 'voting' )
#
#     port:                Optionnal : Number - etcd port number - Default ( etcd_defaults.port )
#     peer_port:           Optionnal : Number - etcd peer port number - Default ( etcd_defaults.peer_port )
#     metrics_port:        Optionnal : Number - etcd metrics port number - Default ( etcd_defaults.metrics_port )

## cluster client
### Allowed client fqdn list
etcd_client: []

### Disallowed client fqdn list
etcd_client_remove: []
